on:
  push:
    branches: main

name: build-and-deploy

jobs:
  R-build-blog:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build GitBook
        run: |-
          Rscript -e "options(bookdown.render.file_scope = FALSE, pandoc.stack.size = '4096m'); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: Deploy GitBook to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_book